//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FateReplayParser.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class frsEntities : DbContext
    {
        public frsEntities()
            : base("name=frsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GamePlayerDetail> GamePlayerDetail { get; set; }
        public virtual DbSet<HeroType> HeroType { get; set; }
        public virtual DbSet<HeroTypeName> HeroTypeName { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerHeroStat> PlayerHeroStat { get; set; }
        public virtual DbSet<PlayerStat> PlayerStat { get; set; }
        public virtual DbSet<Ranking> Ranking { get; set; }
        public virtual DbSet<Server> Server { get; set; }
    }
}
