//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FateReplayParser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameplayerdetail
    {
        public int GamePlayerDetailID { get; set; }
        public int FK_GameID { get; set; }
        public int FK_PlayerID { get; set; }
        public int FK_ServerID { get; set; }
        public int FK_HeroTypeID { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
        public int Assists { get; set; }
        public string Team { get; set; }
        public string Result { get; set; }
        public int ScoreDiff { get; set; }
        public int ELODiff { get; set; }
        public int GoldSpent { get; set; }
        public double DamageDealt { get; set; }
        public double DamageTaken { get; set; }
        public int HeroLevel { get; set; }
    
        public virtual game game { get; set; }
        public virtual herotype herotype { get; set; }
        public virtual server server { get; set; }
    }
}
