//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FateReplayParser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class herotypename
    {
        public int HeroTypeNameID { get; set; }
        public int FK_HeroTypeID { get; set; }
        public string Language { get; set; }
        public string HeroName { get; set; }
        public string HeroTitle { get; set; }
    
        public virtual herotype herotype { get; set; }
    }
}
