//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplayParser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerHeroStat
    {
        public int PlayerHeroStatID { get; set; }
        public int FK_PlayerID { get; set; }
        public int FK_ServerID { get; set; }
        public int FK_HeroTypeID { get; set; }
        public int HeroPlayCount { get; set; }
        public int TotalHeroKills { get; set; }
        public int TotalHeroDeaths { get; set; }
        public int TotalHeroAssists { get; set; }
    
        public virtual HeroType HeroType { get; set; }
        public virtual Server Server { get; set; }
    }
}
