//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplayParser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fa_ranking_systemEntities : DbContext
    {
        public fa_ranking_systemEntities()
            : base("name=fa_ranking_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Game> Game { get; set; }
        public DbSet<GamePlayerDetail> GamePlayerDetail { get; set; }
        public DbSet<HeroType> HeroType { get; set; }
        public DbSet<HeroTypeName> HeroTypeName { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<PlayerBanInfo> PlayerBanInfo { get; set; }
        public DbSet<PlayerHeroStat> PlayerHeroStat { get; set; }
        public DbSet<PlayerStat> PlayerStat { get; set; }
        public DbSet<Ranking> Ranking { get; set; }
        public DbSet<Server> Server { get; set; }
    }
}
