//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplayParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GamePlayerDetail = new HashSet<GamePlayerDetail>();
        }
    
        public int GameID { get; set; }
        public string GameName { get; set; }
        public System.DateTime PlayedDate { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Result { get; set; }
        public string MapVersion { get; set; }
        public string ReplayUrl { get; set; }
        public string MatchType { get; set; }
        public string Log { get; set; }
        public int FK_ServerID { get; set; }
        public int TeamOneWinCount { get; set; }
        public int TeamTwoWinCount { get; set; }
    
        public virtual ICollection<GamePlayerDetail> GamePlayerDetail { get; set; }
        public virtual Server Server { get; set; }
    }
}
