//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplayParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayerDetail
    {
        public int GamePlayerDetailID { get; set; }
        public int FK_GameID { get; set; }
        public int FK_PlayerID { get; set; }
        public int FK_ServerID { get; set; }
        public int FK_HeroTypeID { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
        public int Assists { get; set; }
        public string Team { get; set; }
        public string Result { get; set; }
        public Nullable<int> ScoreDiff { get; set; }
        public Nullable<int> ELODiff { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual HeroType HeroType { get; set; }
        public virtual Server Server { get; set; }
    }
}
