//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplayParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroType
    {
        public HeroType()
        {
            this.GamePlayerDetail = new HashSet<GamePlayerDetail>();
            this.HeroTypeName = new HashSet<HeroTypeName>();
            this.PlayerHeroStat = new HashSet<PlayerHeroStat>();
        }
    
        public int HeroTypeID { get; set; }
        public string HeroUnitTypeID { get; set; }
    
        public virtual ICollection<GamePlayerDetail> GamePlayerDetail { get; set; }
        public virtual ICollection<HeroTypeName> HeroTypeName { get; set; }
        public virtual ICollection<PlayerHeroStat> PlayerHeroStat { get; set; }
    }
}
