//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplayParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerBanInfo
    {
        public int PlayerBanID { get; set; }
        public int FK_PlayerID { get; set; }
        public int FK_ServerID { get; set; }
        public System.DateTime BannedDateFrom { get; set; }
        public System.DateTime BannedDateTo { get; set; }
        public string BannedBy { get; set; }
        public string BannedReason { get; set; }
        public Nullable<System.DateTime> UnbannedOn { get; set; }
        public string UnbannedBy { get; set; }
        public string UnbannedReason { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
